### ISSUE TITLE
Question: go-ceph and rgw libraries

### ISSUE THREAD

**Issue by BlaineEXE** [thotz/cosi-driver-ceph#1]
I see this library is used: https://github.com/QuentinPerez/go-radosgw

I don't see any use of it in Rook today. It seems that it doesn't use `radosgw-admin`. Does that mean that it uses the Admin API? I'm curious if this is something that might be good to add into go-ceph.

**Comment by thotz** [comment]
@BlaineEXE : please refer https://github.com/ceph/go-ceph/discussions/492, @leseb is working on the same. I am using this admins api library for the time being. and will switch accordingly

**Comment by BlaineEXE** [comment]
Sure. Closing this now that I have commented there.
